# Generated by Django 4.2.7 on 2025-07-12 20:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Party name', max_length=200)),
                ('document', models.CharField(help_text='Document number (CPF, CNPJ, etc.)', max_length=20, validators=[django.core.validators.RegexValidator(message='Document must contain only numbers, dots, hyphens and slashes', regex='^[\\d\\.\\-/]+$')])),
                ('category', models.CharField(choices=[('EXEQUENTE', 'Exequente'), ('EXECUTADA', 'Executada'), ('REQUERENTE', 'Requerente'), ('REQUERIDO', 'Requerido'), ('AUTOR', 'Autor'), ('RÉU', 'Réu'), ('TERCEIRO', 'Terceiro')], help_text='Party category in the process', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Party email address', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Party phone number', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('process', models.ForeignKey(help_text='Related legal process', on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='processes.process')),
            ],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'Parties',
                'ordering': ['name'],
                'unique_together': {('process', 'document')},
            },
        ),
    ]
