# Generated by Django 4.2.7 on 2025-07-12 20:15

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_number', models.CharField(help_text='Process number (e.g., 1004030-81.2016.0.00.0008)', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], default='active', max_length=20)),
                ('process_type', models.CharField(choices=[('digital', 'Digital'), ('physical', 'Physical')], default='digital', max_length=20)),
                ('process_class', models.CharField(help_text='Process class (e.g., Execução de Título Extrajudicial)', max_length=200)),
                ('subject', models.CharField(help_text='Process subject (e.g., Locação de Imóvel)', max_length=200)),
                ('judge', models.CharField(help_text='Judge name', max_length=100)),
                ('court', models.CharField(blank=True, help_text='Court name', max_length=200)),
                ('jurisdiction', models.CharField(blank=True, help_text='Jurisdiction information', max_length=200)),
                ('district', models.CharField(blank=True, help_text='District information', max_length=200)),
                ('action_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Action value in currency', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('distribution_date', models.DateField(blank=True, help_text='Process distribution date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Process',
                'verbose_name_plural': 'Processes',
                'ordering': ['-created_at'],
            },
        ),
    ]
